### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by wangfeng22** [Ashutosh-kv/JARVIS#1]
i don't konw how to  import python package. i can't install package by pip

**Comment by prithvik1998** [comment]
> i don't konw how to import python package. i can't install package by pip

yess you can just type pip install - package name

**Comment by mittyparmar** [comment]
@wangfeng22 you still have this issue ? There are multiple ways of installing python and if you are not able to run pip command it appears you are either using py console or something else. 
would you mind sharing a screenshot if you still have this issue.

**Comment by wangfeng22** [comment]
thank you.guys
