### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by perryhq** [Ashutosh-kv/JARVIS#9]
When I enter the commands to play a song, the assistant tells to me that C:\\users\\myuser\\music is not recognizable as a command. How do I fix that?

**Comment by saran-gangster** [comment]
use C:\\users\\myuser\\music
double slash

**Comment by krushna06** [comment]
same even in mine

**Comment by Atta2cool** [comment]
i am having a issui that the songs name is music1, music2 etc. the command is also music = [music1, music2, music3, music4]
imm having the issui that is says music1 not recognized.
